services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 3081:8081
    environment:
      - NODE_ENV=development
    volumes:
    networks:
      - microfrontends
    container_name: mf-auth

  profile:
    build:
      context: ./profile
      dockerfile: Dockerfile
    ports:
      - 3082:8082
    environment:
      - NODE_ENV=development

    networks:
      - microfrontends
    container_name: mf-profile

  feeds:
    build:
      context: ./feeds
      dockerfile: Dockerfile
    ports:
      - 3083:8083
    environment:
      - NODE_ENV=development

    networks:
      - microfrontends
    container_name: mf-feeds

  shared:
    build:
      context: ./shared
      dockerfile: Dockerfile
    ports:
      - 3084:8084
    environment:
      - NODE_ENV=development

    networks:
      - microfrontends
    container_name: mf-shared
    
  host:
    build:
      context: ./host
      dockerfile: Dockerfile
    ports:
      - 3080:8080
    environment:
      - NODE_ENV=development

    networks:
      - microfrontends
    container_name: mf-host
    depends_on:
      - auth
      - profile
      - feeds
      - shared

networks:
  microfrontends:
    driver: bridge